# Generated by Django 5.0.6 on 2024-05-09 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lloguer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('automovil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lloguer.automobil')),
            ],
        ),
    ]
